language: ruby
sudo: false
branches:
  only:
  - master
before_install:
- set -e
- openssl aes-256-cbc -K $encrypted_72e767f5966c_key -iv $encrypted_72e767f5966c_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- git config --global user.email "travis@seedramp.com"
- git config --global user.name "travis"
install:
- travis_retry bundle install
script:
- make
- git checkout git@github.com:yegor256/seedramp.git tmp
- cd tmp
- rm -rf *
- mv ../target .
- git add .
- git commit -am 'deploy  '
- git push origin gh-pages
- cd ..
- rm -rf tmp
